<b>Welcome!</b>

This notebook was built for training purposes... so, do whatever you like with it! The idea being to give people newer to Python the chance to execute code and make changes to variables and calculations and then see the impacts. We'll use some markdown cells to provide some level of organization and direction. But not much.<br><br>
The data and visualizations are based on the 2026 World Cup! (2026-07-10)

In [1]:
# Simple input of name and welcome message
name = input("Please enter your name: ")
print(f"Hello, {name}! We're going to mess around with some graphs!")

Hello, Larry Learner! We're going to mess around with some graphs!

<b>Do our imports of packages and files</b><br>
-- csvs will be provided/ available<br>
-- Being able to pull directly from kaggle does enable you to pull the freshest data<br>
-- If your csvs are in the same directory as this notebook, you shouldn't have to provide any directory info

In [2]:
import pandas as pd
import plotly as plt
import plotly.graph_objects as go
from kaggle.api.kaggle_api_extended import KaggleApi

pd.set_option('display.max_columns', None)

In [3]:
api = KaggleApi()
api.authenticate()

dataset_path = "swaptr/fifa-wc-2026-players"
print("Downloading dataset...")
api.dataset_download_files(dataset_path, path="./", unzip=True)
print("Download complete! Your CSV files are ready.")

Downloading dataset...
Dataset URL: https://www.kaggle.com/datasets/swaptr/fifa-wc-2026-players
Download complete! Your CSV files are ready.

In [4]:
# Directories and file names (if needed)
file_directory = r''
data_file_name = 'players.csv'
country_colors_file_name = 'country_colors.csv'

<b>Take a look at the data</b><br>
Ok! We should be able to now take a look at the data and add some calculated fields we'll use in our graphs.

In [5]:
df = pd.read_csv("players.csv")
df_country_colors = pd.read_csv("country_colors.csv")
# Add color columns from df_country_colors to df based on matching country names
df = df.merge(df_country_colors, how='left', left_on='team_country', right_on='Country')
df['age_years'] = df['age'].str.extract(r'(\d+)').astype(float)
df['position_first'] = df['position'].str.split(',').str[0]
df['pens_missed'] = df['pens_att'] - df['pens_made']
df.head(5)

,player,team,team_country,position,age,birth_year,club,games,games_starts,minutes,minutes_90s,goals,assists,goals_assists,goals_pens,pens_made,pens_att,cards_yellow,cards_red,goals_per90,assists_per90,goals_assists_per90,goals_pens_per90,goals_assists_pens_per90,shots,shots_on_target,shots_on_target_pct,shots_per90,shots_on_target_per90,goals_per_shot,goals_per_shot_on_target,minutes_per_game,minutes_pct,minutes_per_start,games_complete,games_subs,minutes_per_sub,unused_subs,points_per_game,on_goals_for,on_goals_against,plus_minus,plus_minus_per90,plus_minus_wowy,cards_yellow_red,fouls,fouled,offsides,crosses,interceptions,tackles_won,pens_won,pens_conceded,own_goals,gk_games,gk_games_starts,gk_minutes,gk_goals_against,gk_goals_against_per90,gk_shots_on_target_against,gk_saves,gk_save_pct,gk_wins,gk_ties,gk_losses,gk_clean_sheets,gk_clean_sheets_pct,gk_pens_att,gk_pens_allowed,gk_pens_saved,gk_pens_missed,gk_pens_save_pct,Country,Primary Color HEX,Secondary Color HEX,age_years,position_first,pens_missed
0,Achref Abada,Algeria,Algeria,DF,27-024,1999,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Algeria,#006233,#D21034,27.0,DF,NaN
1,Adil Boulbina,Algeria,Algeria,FW,23-068,2003,NaN,2,0,19.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00,0.0,0.0,NaN,0.00,0.00,NaN,NaN,10.0,5.3,NaN,0,2,10.0,2,0.0,0.0,0.0,0.0,0.00,1.06,0.0,0.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Algeria,#006233,#D21034,23.0,FW,0.0
2,Amine Gouiri,Algeria,Algeria,FW,26-143,2000,Marseille,4,3,251.0,2.8,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.36,0.0,0.36,0.36,0.36,3.0,2.0,66.7,1.08,0.72,0.33,0.5,63.0,69.7,73.0,0,1,33.0,0,1.0,4.0,5.0,-1.0,-0.36,2.12,0.0,1.0,1.0,0.0,1.0,0.0,1.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Algeria,#006233,#D21034,26.0,FW,0.0
3,Anis Hadj Moussa,Algeria,Algeria,MF,24-148,2002,Feyenoord,3,1,98.0,1.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00,2.0,0.0,0.0,1.84,0.00,0.00,NaN,33.0,27.2,63.0,0,2,18.0,1,1.0,1.0,2.0,-1.0,-0.92,0.11,0.0,0.0,2.0,0.0,5.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Algeria,#006233,#D21034,24.0,MF,0.0
4,Aïssa Mandi,Algeria,Algeria,DF,34-260,1991,Lille,4,4,360.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00,0.0,0.0,NaN,0.00,0.00,NaN,NaN,90.0,100.0,90.0,4,0,NaN,0,1.0,5.0,9.0,-4.0,-1.00,NaN,0.0,0.0,5.0,0.0,0.0,4.0,3.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Algeria,#006233,#D21034,34.0,DF,0.0

In [6]:
# Print vertial list of column names from df
for column in df.columns:
    print(column)

player
team
team_country
position
age
birth_year
club
games
games_starts
minutes
minutes_90s
goals
assists
goals_assists
goals_pens
pens_made
pens_att
cards_yellow
cards_red
goals_per90
assists_per90
goals_assists_per90
goals_pens_per90
goals_assists_pens_per90
shots
shots_on_target
shots_on_target_pct
shots_per90
shots_on_target_per90
goals_per_shot
goals_per_shot_on_target
minutes_per_game
minutes_pct
minutes_per_start
games_complete
games_subs
minutes_per_sub
unused_subs
points_per_game
on_goals_for
on_goals_against
plus_minus
plus_minus_per90
plus_minus_wowy
cards_yellow_red
fouls
fouled
offsides
crosses
interceptions
tackles_won
pens_won
pens_conceded
own_goals
gk_games
gk_games_starts
gk_minutes
gk_goals_against
gk_goals_against_per90
gk_shots_on_target_against
gk_saves
gk_save_pct
gk_wins
gk_ties
gk_losses
gk_clean_sheets
gk_clean_sheets_pct
gk_pens_att
gk_pens_allowed
gk_pens_saved
gk_pens_missed
gk_pens_save_pct
Country
Primary Color HEX
Secondary Color HEX
age_years
position_first
pens_missed

<b>Make a Scatter Plot</b>
Next, we'll take a look at some of the data relationships we have at the player level by making a scatter plot. Feel free to try out different combinations of fields to see if there any interesting or noteworthy data relationships.

In [7]:
scatter_field_sum_x = 'age_years'
scatter_field_sum_y = 'goals_assists'
scatter_global_font = 'Arial'
scatter_title_font_size = 24
scatter_title = f"Scatter Plot of {scatter_field_sum_y} vs {scatter_field_sum_x} for Players in the 2026 World Cup"

In [10]:
# Scatter plot using plotly that shows the relationship between player age_years and goals_assists. Color should be by Primary Color HEX. Hover should show player name, team_country, age_years, club, position_first, and goals_assists. Only include players with one or more goals_assists
df_filtered_scatter = df[df[scatter_field_sum_y] > 0]

fig = go.Figure()
fig.add_trace(
    go.Scatter(
    x=df_filtered_scatter[scatter_field_sum_x],
    y=df_filtered_scatter[scatter_field_sum_y],
    mode='markers',
    marker=dict(
        color=df_filtered_scatter['Primary Color HEX'],  # Color by Primary Color HEX
        size=15,
        line=dict(width=1, color='DarkSlateGrey')
    ),
    text=df_filtered_scatter.apply(lambda row: f"Player: {row['player']}<br>Country: {row['team_country']}<br>Club: {row['club']}<br>Position: {row['position_first']}<br>{scatter_field_sum_y}: {row[scatter_field_sum_y]}<br>{scatter_field_sum_x}: {row[scatter_field_sum_x]}", axis=1),
    hoverinfo='text'
)
)
# Display the chart
fig.update_layout(
    xaxis_title=scatter_field_sum_x.replace('_', ' ').title(),
    yaxis_title=scatter_field_sum_y.replace('_', ' ').title(),
    font=dict(
        family=scatter_global_font
,
        size=14,
        color="Black"
    ),
    title=dict(
            text=f"<b>{scatter_title}</b>",
            font=dict(
                family=scatter_global_font,
                size=scatter_title_font_size,
                color="Black"
            )
        ),
    template='plotly_white'
)
fig.show()

<b>Make a stacked bar chart</b><br>
The following is a look at penalties made and missed by country. It's also an example of a dark mode themed graph. We can play around with aesthetics here to see what has the most impact and what we like.

In [11]:
# User variables for penalties graph
penalties_outer_background = '#010b1c'
penalties_inner_background = '#01122e'
penalties_missed_bar_color = '#e33b3b'
penalaties_made_bar_color = '#66c46e'
penalties_global_font = 'Arial'
penalties_title_font_size = 24
penalties_font_color = 'white'

In [12]:
# Stacked bar chart from df that shows pens_made vs pens_attempted by team_country. Only include countries with one or more pens_attempted. Color for pens_made should be green and color for pens_missed should be red. Hover should show team_country, pens_made, pens_missed, and pens_attempted.

df_pens_filtered_stacked = df[df['pens_att'] > 0].groupby('team_country', as_index=False).agg({
    'pens_made': 'sum',
    'pens_missed': 'sum',
    'pens_att': 'sum'
})

fig = go.Figure()
fig.add_trace(
    go.Bar(
        x=df_pens_filtered_stacked['team_country'],
        y=df_pens_filtered_stacked['pens_made'],
        name='Pens Made',
        marker_color=penalaties_made_bar_color
    )
)
fig.add_trace(
    go.Bar(
        x=df_pens_filtered_stacked['team_country'],
        y=df_pens_filtered_stacked['pens_missed'],
        name='Pens Missed',
        marker_color=penalties_missed_bar_color
    )
)
fig.update_layout(
    barmode='stack',
    xaxis=dict(
        title=f"<b>Countries</b>",
        showgrid=False
        ),
    yaxis=dict(
        title=f"<b>Pens Attempted</b>",
        side="left",
        showgrid=False,
        tickformat=',d', # Format y-axis ticks as integers
        dtick=1
        ),
    font=dict(
        family=penalties_global_font,
        size=14,
        color=penalties_font_color
    ),
    title=dict(
            text=f"<b>Made and Missed Penalties by Country</b>",
            font=dict(
                family=penalties_global_font,
                size=penalties_title_font_size,
                color=penalties_font_color
            )
        ),
    paper_bgcolor= penalties_outer_background,
    plot_bgcolor=penalties_inner_background,
    template='plotly_white'
)
fig.show()

<b>Next we'll be making graphs that are a bit more complex: Pareto charts</b><br>
Pareto charts focus on showing the primary inputs or contributors on a result. There especially helpful when there are MANY contributors. Even more so when a small group of those contributors have an outsized impact on the result. These charts are tied to the 80/20 rule which states: in a lot of cases, 80% of your outputs (results) are driven by 20% of your inputs (contributors). Note, it doesn't have to be an 80/20 split for a Pareto to still be the right choice for a graph. <br><br>
Here, we'll look at the impact of countries and then individual players on overall goal output for the 2026 World Cup.

In [13]:
df_goals_check = df.sort_values(by='goals', ascending=False)
df_goals_check.head(5)

,player,team,team_country,position,age,birth_year,club,games,games_starts,minutes,minutes_90s,goals,assists,goals_assists,goals_pens,pens_made,pens_att,cards_yellow,cards_red,goals_per90,assists_per90,goals_assists_per90,goals_pens_per90,goals_assists_pens_per90,shots,shots_on_target,shots_on_target_pct,shots_per90,shots_on_target_per90,goals_per_shot,goals_per_shot_on_target,minutes_per_game,minutes_pct,minutes_per_start,games_complete,games_subs,minutes_per_sub,unused_subs,points_per_game,on_goals_for,on_goals_against,plus_minus,plus_minus_per90,plus_minus_wowy,cards_yellow_red,fouls,fouled,offsides,crosses,interceptions,tackles_won,pens_won,pens_conceded,own_goals,gk_games,gk_games_starts,gk_minutes,gk_goals_against,gk_goals_against_per90,gk_shots_on_target_against,gk_saves,gk_save_pct,gk_wins,gk_ties,gk_losses,gk_clean_sheets,gk_clean_sheets_pct,gk_pens_att,gk_pens_allowed,gk_pens_saved,gk_pens_missed,gk_pens_save_pct,Country,Primary Color HEX,Secondary Color HEX,age_years,position_first,pens_missed
41,Lionel Messi,Argentina,Argentina,FW,39-015,1987,Inter Miami,5,4,410.0,4.6,8.0,1.0,9.0,8.0,0.0,2.0,0.0,0.0,1.76,0.22,1.98,1.76,1.98,29.0,17.0,58.6,6.37,3.73,0.28,0.47,82.0,85.4,95.0,3,1,31.0,0,3.0,12.0,4.0,8.0,1.76,0.47,0.0,2.0,13.0,2.0,29.0,0.0,6.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Argentina,#74ACDF,#FFD700,39.0,FW,2.0
811,Erling Haaland,Norway,Norway,FW,25-353,2000,Manchester City,4,4,360.0,4.0,7.0,0.0,7.0,7.0,0.0,0.0,0.0,0.0,1.75,0.00,1.75,1.75,1.75,18.0,12.0,66.7,4.50,3.00,0.39,0.58,90.0,80.0,90.0,4,0,NaN,1,3.0,11.0,5.0,6.0,1.50,4.50,0.0,5.0,3.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Norway,#EF2B2D,#002868,25.0,FW,0.0
477,Kylian Mbappé,France,France,FW,27-201,1998,Real Madrid,5,5,439.0,4.9,7.0,2.0,9.0,6.0,1.0,1.0,0.0,0.0,1.44,0.41,1.85,1.23,1.64,26.0,17.0,65.4,5.33,3.49,0.23,0.35,88.0,97.6,88.0,2,0,NaN,0,3.0,13.0,2.0,11.0,2.26,-5.93,0.0,5.0,5.0,2.0,2.0,0.0,1.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,France,#0055A4,#EF4135,27.0,FW,0.0
451,Harry Kane,England,England,FW,32-346,1993,Bayern Munich,5,5,442.0,4.9,6.0,1.0,7.0,4.0,2.0,2.0,0.0,0.0,1.22,0.20,1.43,0.81,1.02,19.0,10.0,52.6,3.87,2.04,0.21,0.40,88.0,98.2,88.0,3,0,NaN,0,2.6,11.0,5.0,6.0,1.22,1.22,0.0,7.0,7.0,1.0,0.0,1.0,2.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,England,#CE1124,#CFCECD,32.0,FW,0.0
1055,Mikel Oyarzabal,Spain,Spain,FW,29-079,1997,Real Sociedad,5,5,389.0,4.3,4.0,1.0,5.0,4.0,0.0,0.0,0.0,0.0,0.93,0.23,1.16,0.93,1.16,19.0,9.0,47.4,4.40,2.08,0.21,0.44,78.0,86.4,78.0,2,0,NaN,0,2.6,7.0,0.0,7.0,1.62,-1.33,0.0,2.0,2.0,0.0,3.0,0.0,3.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spain,#AA151B,#FBC02D,29.0,FW,0.0

In [14]:
# Sort df so you can calculate running some
df_pareto_players = df.sort_values(by='goals', ascending=False).reset_index(drop=True)

# Calculate the cumulative sum of goals
df_pareto_players['cumulative_goals'] = df_pareto_players['goals'].cumsum()
df_pareto_players['cumulative_percentage'] = df_pareto_players['cumulative_goals'] / df_pareto_players['goals'].sum() * 100

In [15]:
df_pareto_players.head(5)

,player,team,team_country,position,age,birth_year,club,games,games_starts,minutes,minutes_90s,goals,assists,goals_assists,goals_pens,pens_made,pens_att,cards_yellow,cards_red,goals_per90,assists_per90,goals_assists_per90,goals_pens_per90,goals_assists_pens_per90,shots,shots_on_target,shots_on_target_pct,shots_per90,shots_on_target_per90,goals_per_shot,goals_per_shot_on_target,minutes_per_game,minutes_pct,minutes_per_start,games_complete,games_subs,minutes_per_sub,unused_subs,points_per_game,on_goals_for,on_goals_against,plus_minus,plus_minus_per90,plus_minus_wowy,cards_yellow_red,fouls,fouled,offsides,crosses,interceptions,tackles_won,pens_won,pens_conceded,own_goals,gk_games,gk_games_starts,gk_minutes,gk_goals_against,gk_goals_against_per90,gk_shots_on_target_against,gk_saves,gk_save_pct,gk_wins,gk_ties,gk_losses,gk_clean_sheets,gk_clean_sheets_pct,gk_pens_att,gk_pens_allowed,gk_pens_saved,gk_pens_missed,gk_pens_save_pct,Country,Primary Color HEX,Secondary Color HEX,age_years,position_first,pens_missed,cumulative_goals,cumulative_percentage
0,Lionel Messi,Argentina,Argentina,FW,39-015,1987,Inter Miami,5,4,410.0,4.6,8.0,1.0,9.0,8.0,0.0,2.0,0.0,0.0,1.76,0.22,1.98,1.76,1.98,29.0,17.0,58.6,6.37,3.73,0.28,0.47,82.0,85.4,95.0,3,1,31.0,0,3.0,12.0,4.0,8.0,1.76,0.47,0.0,2.0,13.0,2.0,29.0,0.0,6.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Argentina,#74ACDF,#FFD700,39.0,FW,2.0,8.0,2.996255
1,Erling Haaland,Norway,Norway,FW,25-353,2000,Manchester City,4,4,360.0,4.0,7.0,0.0,7.0,7.0,0.0,0.0,0.0,0.0,1.75,0.00,1.75,1.75,1.75,18.0,12.0,66.7,4.50,3.00,0.39,0.58,90.0,80.0,90.0,4,0,NaN,1,3.0,11.0,5.0,6.0,1.50,4.50,0.0,5.0,3.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Norway,#EF2B2D,#002868,25.0,FW,0.0,15.0,5.617978
2,Kylian Mbappé,France,France,FW,27-201,1998,Real Madrid,5,5,439.0,4.9,7.0,2.0,9.0,6.0,1.0,1.0,0.0,0.0,1.44,0.41,1.85,1.23,1.64,26.0,17.0,65.4,5.33,3.49,0.23,0.35,88.0,97.6,88.0,2,0,NaN,0,3.0,13.0,2.0,11.0,2.26,-5.93,0.0,5.0,5.0,2.0,2.0,0.0,1.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,France,#0055A4,#EF4135,27.0,FW,0.0,22.0,8.239700
3,Harry Kane,England,England,FW,32-346,1993,Bayern Munich,5,5,442.0,4.9,6.0,1.0,7.0,4.0,2.0,2.0,0.0,0.0,1.22,0.20,1.43,0.81,1.02,19.0,10.0,52.6,3.87,2.04,0.21,0.40,88.0,98.2,88.0,3,0,NaN,0,2.6,11.0,5.0,6.0,1.22,1.22,0.0,7.0,7.0,1.0,0.0,1.0,2.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,England,#CE1124,#CFCECD,32.0,FW,0.0,28.0,10.486891
4,Mikel Oyarzabal,Spain,Spain,FW,29-079,1997,Real Sociedad,5,5,389.0,4.3,4.0,1.0,5.0,4.0,0.0,0.0,0.0,0.0,0.93,0.23,1.16,0.93,1.16,19.0,9.0,47.4,4.40,2.08,0.21,0.44,78.0,86.4,78.0,2,0,NaN,0,2.6,7.0,0.0,7.0,1.62,-1.33,0.0,2.0,2.0,0.0,3.0,0.0,3.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spain,#AA151B,#FBC02D,29.0,FW,0.0,32.0,11.985019

In [16]:
# Pareto switch variables
## You set
pareto_threshold = 20  # 80% of goals
## Calculated
pareto_player_count = df_pareto_players[df_pareto_players['cumulative_percentage'] < pareto_threshold].shape[0]
pareto_other_sum = df_pareto_players[df_pareto_players['cumulative_percentage'] >= pareto_threshold]['goals'].sum()
pareto_other_percentage = pareto_other_sum / df_pareto_players['goals'].sum() * 100
pareto_other_player_count = df_pareto_players[df_pareto_players['cumulative_percentage'] >= pareto_threshold].shape[0]
pareto_total_goals = df_pareto_players['goals'].sum()

pareto_title = f"Pareto Analysis: {pareto_player_count} Players Account for {pareto_threshold}% of the {pareto_total_goals:.0f} Total Goals Scored at the 2026 World Cup"

In [17]:
# Create list of df_pareto players that are above the pareto threshold
df_pareto_players_above_threshold = df_pareto_players[df_pareto_players['cumulative_percentage'] < pareto_threshold]
# Create list of player names from df_pareto players that are above the pareto threshold
pareto_players_above_threshold = df_pareto_players_above_threshold['player'].tolist()
# Create list of goal values from df_pareto players that are above the pareto threshold
pareto_goals_above_threshold = df_pareto_players_above_threshold['goals'].tolist()
# Create list of cumulative goal percentages from df_pareto players that are above the pareto threshold
pareto_cumulative_goals_above_threshold = df_pareto_players_above_threshold['cumulative_percentage'].tolist()
pareto_percentage_labels = [f"{percentage:.1f}%" for percentage in pareto_cumulative_goals_above_threshold]

In [18]:
# Pareto aesthetic variables
pareto_player_graph_outer_background = 'white'
pareto_player_graph_inner_background = 'white'
pareto_player_line_color = "crimson"
pareto_player_bar_color = "#029c75"
pareto_player_bar_opacity = 0.5
pareto_player_show_legend = False
pareto_player_global_font = "Arial"
pareoto_player_title_font_size = 24

In [19]:
# Make pareto chart with plotly
fig = go.Figure()

#Add the primary Bar Chart trace (Left Y-Axis)
fig.add_trace(
    go.Bar(
        x=pareto_players_above_threshold,
        y=pareto_goals_above_threshold,
        name="Player",
        marker_color=pareto_player_bar_color,
        opacity=pareto_player_bar_opacity,
        yaxis='y1',
        customdata=df_pareto_players_above_threshold[['team_country']].values,  # Add country data for hover
        hovertemplate=(
            '<b>%{x}</b><br>'+
            'Goals: %{y}<br>'+
            'Country: %{customdata[0]}<br>'+
            '<extra></extra>')
    )
)

# 6. Add the secondary Line Chart trace (Right Y-Axis)
fig.add_trace(
    go.Scatter(
        x=df_pareto_players_above_threshold['player'],
        y=pareto_cumulative_goals_above_threshold,
        name="Cumulative %",
        mode="lines+markers+text",
        text=pareto_percentage_labels,
        textposition='top center',
        textfont=dict(
            color='black', 
            size=14
        ),
        line=dict(
            color=pareto_player_line_color, 
            width=2, 
            dash='dot',
            shape='spline'
        ),
        marker=dict(
            color=pareto_player_line_color, 
            size=16,
            symbol='circle'
        ),
        yaxis="y2"  # Points this trace to the secondary y-axis
    )
)

# 7. Configure layout with dual axes
fig.update_layout(
    showlegend=pareto_player_show_legend,
    xaxis=dict(
        title="Players",
        showgrid=False
        ),
    yaxis=dict(
        title="Goals",
        side="left",
        showgrid=False
        ),
    yaxis2=dict(
        title=f"Cumulative % of all Goals",
        side="right",
        overlaying="y",  # Ensures it overlays the primary y-axis
        range=[0, 105],  # Pads the top slightly for visual clarity
        ticksuffix="%",  # Adds percent signs to right-hand axis labels
        showgrid=False
    ),
    font=dict(
        family=pareto_player_global_font,
        size=14,
        color="Black"
    ),
    title=dict(
            text=f"<b>{pareto_title}</b>",
            font=dict(
                family=pareto_player_global_font,
                size=pareoto_player_title_font_size,
                color="Black"
            )
        ),
    legend=dict(x=0.8, y=1.1), # Positions the legend neatly
    paper_bgcolor= pareto_player_graph_outer_background,
    plot_bgcolor=pareto_player_graph_inner_background,
    template="plotly_white",
    )
# Display the interactive chart
fig.show()

<b>Now we'll make a country based Pareto!</b>

In [20]:
# Create a dataframe from df of countries and total goals scored by players from that country
df_country_goals = df.groupby(['team_country', 'Primary Color HEX', 'Secondary Color HEX'], as_index=False).agg({'goals': 'sum'}).rename(columns={'goals': 'total_goals'})

# Sort df_country_goals by total_goals in descending order
df_pareto_country = df_country_goals.sort_values(by='total_goals', ascending=False)
# Add cumulative goals and cumulative percentage columns to df_pareto_country
df_pareto_country['cumulative_goals'] = df_pareto_country['total_goals'].cumsum()
df_pareto_country['cumulative_percentage'] = df_pareto_country['cumulative_goals'] / df_pareto_country['total_goals'].sum() * 100

In [21]:
# Country Pareto switch variables
## You set
country_pareto_threshold = 40 # % of total goals
## Calculated
country_pareto_player_count = df_pareto_country[df_pareto_country['cumulative_percentage'] < country_pareto_threshold].shape[0]
country_pareto_other_sum = df_pareto_country[df_pareto_country['cumulative_percentage'] >= country_pareto_threshold]['total_goals'].sum()
country_pareto_other_percentage = country_pareto_other_sum / df_pareto_country['total_goals'].sum() * 100
country_pareto_other_player_count = df_pareto_country[df_pareto_country['cumulative_percentage'] >= country_pareto_threshold].shape[0]
country_pareto_total_goals = df_pareto_country['total_goals'].sum()

country_pareto_title = f"Pareto Analysis: {country_pareto_player_count} Countries Account for {country_pareto_threshold}% of the {country_pareto_total_goals:.0f} Total Goals Scored at the 2026 World Cup"

In [22]:
# Create list of df_pareto countries that are above the pareto threshold
df_pareto_countries_above_threshold = df_pareto_country[df_pareto_country['cumulative_percentage'] < country_pareto_threshold]

In [23]:
# Pareto aesthetic variables
pareto_country_graph_outer_background = 'white'
pareto_country_graph_inner_background = 'white'
pareto_country_line_color = "crimson"
pareto_country_bar_opacity = 0.5
pareto_country_show_legend = False
pareto_country_global_font = "Arial"
pareto_country_title_font_size = 24

In [24]:
# Make pareto chart with plotly
fig = go.Figure()

#Add the primary Bar Chart trace (Left Y-Axis)
fig.add_trace(
    go.Bar(
        x=df_pareto_countries_above_threshold['team_country'],
        y=df_pareto_countries_above_threshold['total_goals'],
        name="Player",
        opacity=pareto_player_bar_opacity,
        marker=dict(
            color=df_pareto_countries_above_threshold['Primary Color HEX'], # Fills the inner bar area
            line=dict(
                color=df_pareto_countries_above_threshold['Secondary Color HEX'], # Sets the border color
                width=4 # Sets the border line width in pixels
            )
        ),
        yaxis='y1',
        customdata=df_pareto_countries_above_threshold[['cumulative_goals']].values,  # Add country data for hover
        hovertemplate=(
            '<b>%{x}</b><br>'+
            'Team Goals: %{y}<br>'+
            'Cumulative Goals: %{customdata[0]}<br>'+
            '<extra></extra>')
    )
)

# 6. Add the secondary Line Chart trace (Right Y-Axis)
fig.add_trace(
    go.Scatter(
        x=df_pareto_countries_above_threshold['team_country'],
        y=df_pareto_countries_above_threshold['cumulative_percentage'],
        name="Cumulative %",
        mode="lines+markers+text",
        text=df_pareto_countries_above_threshold['cumulative_percentage'].apply(lambda x: f"{x:.1f}%"),  # Format as percentage 
        textposition='top center',
        textfont=dict(
            color='black', 
            size=14
        ),
        line=dict(
            color=pareto_country_line_color, 
            width=2, 
            dash='dot',
            shape='spline'
        ),
        marker=dict(
            color=pareto_country_line_color, 
            size=16,
            symbol='circle'
        ),
        yaxis="y2"  # Points this trace to the secondary y-axis
    )
)

# 7. Configure layout with dual axes
fig.update_layout(
    showlegend=pareto_country_show_legend,
    xaxis=dict(
        title="Countries",
        showgrid=False
        ),
    yaxis=dict(
        title="Goals",
        side="left",
        showgrid=False
        ),
    yaxis2=dict(
        title=f"Cumulative % of all Goals",
        side="right",
        overlaying="y",  # Ensures it overlays the primary y-axis
        range=[0, 105],  # Pads the top slightly for visual clarity
        ticksuffix="%",  # Adds percent signs to right-hand axis labels
        showgrid=False
    ),
    font=dict(
        family=pareto_country_global_font,
        size=14,
        color="Black"
    ),
    title=dict(
            text=f"<b>{country_pareto_title}</b>",
            font=dict(
                family=pareto_country_global_font,
                size=pareto_country_title_font_size,
                color="Black"
            )
        ),
    legend=dict(x=0.8, y=1.1), # Positions the legend neatly
    paper_bgcolor= pareto_country_graph_outer_background,
    plot_bgcolor=pareto_country_graph_inner_background,
    template="plotly_white",
    )
# Display the interactive chart
fig.show()